[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.check]
dependencies = [
    { name = "check", path = "boot" },
    { name = "check", path = "kernel" }
]

[tasks.build]
dependencies = [
    { name = "build", path = "boot" },
    { name = "build", path = "kernel" }
]

[tasks.image]
dependencies = ["build"]
script = '''
set -eu
qemu-img create -f raw disk.img 200M
mkfs.fat -n 'COSMOS' -s 2 -f 2 -R 32 -F32 disk.img
mkdir -p mnt
sudo mount -o loop disk.img mnt
sudo mkdir -p mnt/EFI/BOOT
sudo cp ./target/x86_64-unknown-uefi/debug/boot.efi ./mnt/EFI/BOOT/BOOTX64.EFI
sudo cp ./target/x86_64-unknown-none-elf/debug/kernel ./mnt/kernel.elf
sudo umount mnt
'''

[tasks.run]
dependencies = ["image"]
script = '''
qemu-system-x86_64 \
    -drive if=pflash,format=raw,readonly,file=/home/vscode/osbook/devenv/OVMF_CODE.fd \
    -drive if=pflash,format=raw,file=/home/vscode/osbook/devenv/OVMF_VARS.fd \
    -drive if=ide,format=raw,media=disk,index=0,file=disk.img \
    -device nec-usb-xhci,id=xhci \
    -device usb-mouse \
    -device usb-kbd \
    -monitor stdio
'''
