[tasks.check]
dependencies = [
    { name = "check", path = "boot" },
    { name = "check", path = "kernel" }
]

[tasks.build]
dependencies = [
    { name = "build", path = "boot" },
    { name = "build", path = "kernel" }
]
