[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features"]
dependencies = ["format"]

[tasks.check]
dependencies = [
    "format",
    "clippy",
]

[tasks.build]
command = "cargo"
args = ["build"]
