[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clippy"]

[tasks.check]
dependencies = [
    "format",
    "clippy",
    "test"
]

[tasks.build]
command = "cargo"
args = ["build", "--target", "x86_64-unknown-uefi"]
